// Parâmetros
var question = '102741481b770e5007caeca12b4bcbf2'; // Nome do campo de escolha (ajuste conforme necessário)

// Lista Lista question choice
var banks = [
    { value: 'ABC_BRASIL', label: 'BANCO ABC BRASIL S.A.' },
    { value: 'ABN_AMRO_CLEARING', label: 'BANCO ABN AMRO CLEARING S.A.' },
    { value: 'AFINZ', label: 'BANCO AFINZ S.A. - BANCO MÚLTIPLO' },
    { value: 'AGIBANK', label: 'BANCO AGIBANK S.A.' },
    { value: 'ALFA', label: 'BANCO ALFA S.A.' },
    { value: 'ANDBANK', label: 'BANCO ANDBANK (BRASIL) S.A.' },
    { value: 'ARBI', label: 'BANCO ARBI S.A.' },
    { value: 'B3', label: 'BANCO B3 S.A.' },
    { value: 'BANDEPE', label: 'BANCO BANDEPE S.A.' },
    { value: 'BARI', label: 'BANCO BARI DE INVESTIMENTOS E FINANCIAMENTOS S.A.' },
    { value: 'BESA', label: 'BANCO BESA S.A.' },
    { value: 'BMG', label: 'BANCO BMG S.A.' },
    { value: 'BNP_PARIBAS', label: 'BANCO BNP PARIBAS BRASIL S.A.' },
    { value: 'BOCOM_BBM', label: 'BANCO BOCOM BBM S.A.' },
    { value: 'BRADESCARD', label: 'BANCO BRADESCARD S.A.' },
    { value: 'BRADESCO_BBI', label: 'BANCO BRADESCO BBI S.A.' },
    { value: 'BRADESCO_BERJ', label: 'BANCO BRADESCO BERJ S.A.' },
    { value: 'BRADESCO_FINANCIAMENTOS', label: 'BANCO BRADESCO FINANCIAMENTOS S.A.' },
    { value: 'BRADESCO', label: 'BANCO BRADESCO S.A.' },
    { value: 'BRASILEIRO_CREDITO', label: 'BANCO BRASILEIRO DE CRÉDITO SOCIEDADE ANÔNIMA' },
    { value: 'BS2', label: 'BANCO BS2 S.A.' },
    { value: 'BTG_PACTUAL', label: 'BANCO BTG PACTUAL S.A.' },
    { value: 'BV', label: 'BANCO BV S.A.' },
    { value: 'C6_CONSIGNADO', label: 'BANCO C6 CONSIGNADO S.A.' },
    { value: 'C6', label: 'BANCO C6 S.A.' },
    { value: 'CAIXA_GERAL', label: 'BANCO CAIXA GERAL - BRASIL S.A.' },
    { value: 'CARGILL', label: 'BANCO CARGILL S.A.' },
    { value: 'CATERPILLAR', label: 'BANCO CATERPILLAR S.A.' },
    { value: 'CEDULA', label: 'BANCO CEDULA S.A.' },
    { value: 'CIFRA', label: 'BANCO CIFRA S.A.' },
    { value: 'CITIBANK', label: 'BANCO CITIBANK S.A.' },
    { value: 'CLASSICO', label: 'BANCO CLASSICO S.A.' },
    { value: 'CNH_INDUSTRIAL', label: 'BANCO CNH INDUSTRIAL CAPITAL S.A.' },
    { value: 'COOPERATIVO_SICOOB', label: 'BANCO COOPERATIVO SICOOB S.A. - BANCO SICOOB' },
    { value: 'COOPERATIVO_SICREDI', label: 'BANCO COOPERATIVO SICREDI S.A.' },
    { value: 'CREDIT_AGRICOLE', label: 'BANCO CRÉDIT AGRICOLE BRASIL S.A.' },
    { value: 'CREDIT_SUISSE', label: 'BANCO CREDIT SUISSE (BRASIL) S.A.' },
    { value: 'CREFISA', label: 'BANCO CREFISA S.A.' },
    { value: 'CSF', label: 'BANCO CSF S.A.' },
    { value: 'AMAZONIA', label: 'BANCO DA AMAZONIA S.A.' },
    { value: 'CHINA_BRASIL', label: 'BANCO DA CHINA BRASIL S.A.' },
    { value: 'DAYCOVAL', label: 'BANCO DAYCOVAL S.A.' },
    { value: 'NACION_ARGENTINA', label: 'BANCO DE LA NACION ARGENTINA' },
    { value: 'PROVINCIA_BUENOS_AIRES', label: 'BANCO DE LA PROVINCIA DE BUENOS AIRES' },
    { value: 'LAGE_LANDEN', label: 'BANCO DE LAGE LANDEN BRASIL S.A.' },
    { value: 'DIGIMAIS', label: 'BANCO DIGIMAIS S.A.' },
    { value: 'DIGIO', label: 'BANCO DIGIO S.A.' },
    { value: 'BRASIL', label: 'BANCO DO BRASIL S.A.' },
    { value: 'ESTADO_SERGIPE', label: 'BANCO DO ESTADO DE SERGIPE S.A.' },
    { value: 'ESTADO_PARA', label: 'BANCO DO ESTADO DO PARÁ S.A.' },
    { value: 'ESTADO_RIO_GRANDE_DO_SUL', label: 'BANCO DO ESTADO DO RIO GRANDE DO SUL S.A.' },
    { value: 'NORDESTE', label: 'BANCO DO NORDESTE DO BRASIL S.A.' },
    { value: 'FATOR', label: 'BANCO FATOR S.A.' },
    { value: 'FIBRA', label: 'BANCO FIBRA S.A.' },
    { value: 'FINAXIS', label: 'BANCO FINAXIS S.A.' },
    { value: 'GENIAL', label: 'BANCO GENIAL S.A.' },
    { value: 'GM', label: 'BANCO GM S.A.' },
    { value: 'GUANABARA', label: 'BANCO GUANABARA S.A.' },
    { value: 'HONDA', label: 'BANCO HONDA S.A.' },
    { value: 'HSBC', label: 'BANCO HSBC S.A.' },
    { value: 'HYUNDAI_CAPITAL', label: 'BANCO HYUNDAI CAPITAL BRASIL S.A.' },
    { value: 'IBM', label: 'BANCO IBM S.A.' },
    { value: 'INBURSA', label: 'BANCO INBURSA S.A.' },
    { value: 'INDUSTRIAL', label: 'BANCO INDUSTRIAL DO BRASIL S.A.' },
    { value: 'INTER', label: 'BANCO INTER S.A.' },
    { value: 'INVESTCRED_UNIBANCO', label: 'BANCO INVESTCRED UNIBANCO S.A.' },
    { value: 'ITAU_CONSIGNADO', label: 'BANCO ITAÚ CONSIGNADO S.A.' },
    { value: 'ITAU_VEICULOS', label: 'BANCO ITAÚ VEÍCULOS S.A.' },
    { value: 'ITAUBANK', label: 'BANCO ITAUBANK S.A.' },
    { value: 'ITAUCARD', label: 'BANCO ITAUCARD S.A.' },
    { value: 'J_SAFRA', label: 'BANCO J. SAFRA S.A.' },
    { value: 'JP_MORGAN', label: 'BANCO J.P. MORGAN S.A.' },
    { value: 'JOHN_DEERE', label: 'BANCO JOHN DEERE S.A.' },
    { value: 'KDB', label: 'BANCO KDB DO BRASIL S.A.' },
    { value: 'KEB_HANA', label: 'BANCO KEB HANA DO BRASIL S.A.' },
    { value: 'KOMATSU', label: 'BANCO KOMATSU DO BRASIL S.A.' },
    { value: 'LETSBANK', label: 'BANCO LETSBANK S.A.' },
    { value: 'LOSANGO', label: 'BANCO LOSANGO S.A. - BANCO MÚLTIPLO' },
    { value: 'LUSO_BRASILEIRO', label: 'BANCO LUSO BRASILEIRO S.A.' },
    { value: 'MASTER_MULTIPLO', label: 'BANCO MASTER MÚLTIPLO S.A.' },
    { value: 'MASTER', label: 'BANCO MASTER S/A' },
    { value: 'MERCANTIL_DO_BRASIL', label: 'BANCO MERCANTIL DO BRASIL S.A.' },
    { value: 'MERCEDES_BENZ', label: 'BANCO MERCEDES-BENZ DO BRASIL S.A.' },
    { value: 'MIZUHO', label: 'BANCO MIZUHO DO BRASIL S.A.' },
    { value: 'MODAL', label: 'BANCO MODAL S.A.' },
    { value: 'MONEO', label: 'BANCO MONEO S.A.' },
    { value: 'MORGAN_STANLEY', label: 'BANCO MORGAN STANLEY S.A.' },
    { value: 'MUFG_BRASIL', label: 'BANCO MUFG BRASIL S.A.' },
    { value: 'ORIGINAL', label: 'BANCO ORIGINAL S.A.' },
    { value: 'PACCAR', label: 'BANCO PACCAR S.A.' },
    { value: 'PAN', label: 'BANCO PAN S.A.' },
    { value: 'PAULISTA', label: 'BANCO PAULISTA S.A.' },
    { value: 'PINE', label: 'BANCO PINE S.A.' },
    { value: 'RABOBANK', label: 'BANCO RABOBANK INTERNATIONAL BRASIL S.A.' },
    { value: 'RANDON', label: 'BANCO RANDON S.A.' },
    { value: 'RCI', label: 'BANCO RCI BRASIL S.A.' },
    { value: 'RENDIMENTO', label: 'BANCO RENDIMENTO S.A.' },
    { value: 'RIBEIRAO_PRETO', label: 'BANCO RIBEIRAO PRETO S.A.' },
    { value: 'RNX', label: 'BANCO RNX S.A.' },
    { value: 'RODOBENS', label: 'BANCO RODOBENS S.A.' },
    { value: 'SAFRA', label: 'BANCO SAFRA S.A.' },
    { value: 'SANTANDER', label: 'BANCO SANTANDER (BRASIL) S.A.' },
    { value: 'SEMEAR', label: 'BANCO SEMEAR S.A.' },
    { value: 'SENFF', label: 'BANCO SENFF S.A.' },
    { value: 'SISTEMA', label: 'BANCO SISTEMA S.A.' },
    { value: 'SOCIETE_GENERALE', label: 'BANCO SOCIETE GENERALE BRASIL S.A.' },
    { value: 'SOFISA', label: 'BANCO SOFISA S.A.' },
    { value: 'STELLANTIS', label: 'BANCO STELLANTIS S.A.' },
    { value: 'SUMITOMO', label: 'BANCO SUMITOMO MITSUI BRASILEIRO S.A.' },
    { value: 'TOPAZIO', label: 'BANCO TOPÁZIO S.A.' },
    { value: 'TOYOTA', label: 'BANCO TOYOTA DO BRASIL S.A.' },
    { value: 'TRIANGULO', label: 'BANCO TRIANGULO S.A.' },
    { value: 'TRICURY', label: 'BANCO TRICURY S.A.' },
    { value: 'VOITER', label: 'BANCO VOITER S.A.' },
    { value: 'VOLKSWAGEN', label: 'BANCO VOLKSWAGEN S.A.' },
    { value: 'VOLVO', label: 'BANCO VOLVO BRASIL S.A.' },
    { value: 'VOTORANTIM', label: 'BANCO VOTORANTIM S.A.' },
    { value: 'VR', label: 'BANCO VR S.A.' },
    { value: 'WESTERN_UNION', label: 'BANCO WESTERN UNION DO BRASIL S.A.' },
    { value: 'WOORI_BANK', label: 'BANCO WOORI BANK DO BRASIL S.A.' },
    { value: 'XCMG', label: 'BANCO XCMG BRASIL S.A.' },
    { value: 'XP', label: 'BANCO XP S.A.' },
    { value: 'YAMAHA_MOTOR', label: 'BANCO YAMAHA MOTOR DO BRASIL S.A.' },
    { value: 'BANCOSEGURO', label: 'BANCOSEGURO S.A.' },
    { value: 'BANESTES', label: 'BANESTES S.A. BANCO DO ESTADO DO ESPIRITO SANTO' },
    { value: 'BANK_OF_AMERICA', label: 'BANK OF AMERICA MERRILL LYNCH BANCO MÚLTIPLO S.A.' },
    { value: 'BCV', label: 'BCV - BANCO DE CRÉDITO E VAREJO S.A.' },
    { value: 'BNY_MELLON', label: 'BNY MELLON BANCO S.A.' },
    { value: 'BRAZA_BANK', label: 'BRAZA BANK S.A. BANCO DE CÂMBIO' },
    { value: 'BRB', label: 'BRB - BANCO DE BRASILIA S.A.' },
    { value: 'CAIXA_ECONOMICA', label: 'CAIXA ECONOMICA FEDERAL' },
    { value: 'CHINA_CONSTRUCTION_BANK', label: 'CHINA CONSTRUCTION BANK (BRASIL) BANCO MÚLTIPLO S/A' },
    { value: 'CITIBANK_NA', label: 'CITIBANK N.A.' },
    { value: 'DAYCOVAL_LEASING', label: 'DAYCOVAL LEASING - BANCO MÚLTIPLO S.A.' },
    { value: 'DEUTSCHE_BANK', label: 'DEUTSCHE BANK S.A. - BANCO ALEMAO' },
    { value: 'DEUTSCHE_SPARKASSEN', label: 'DEUTSCHE SPARKASSEN LEASING DO BRASIL BANCO MÚLTIPLO S.A.' },
    { value: 'EBURY', label: 'EBURY BANCO DE CÂMBIO S.A.' },
    { value: 'GOLDMAN_SACHS', label: 'GOLDMAN SACHS DO BRASIL BANCO MULTIPLO S.A.' },
    { value: 'HIPERCARD', label: 'HIPERCARD BANCO MÚLTIPLO S.A.' },
    { value: 'ICBC', label: 'ICBC DO BRASIL BANCO MÚLTIPLO S.A.' },
    { value: 'INTESA_SANPAOLO', label: 'INTESA SANPAOLO BRASIL S.A. - BANCO MÚLTIPLO' },
    { value: 'ITAU_UNIBANCO_HOLDING', label: 'ITAÚ UNIBANCO HOLDING S.A.' },
    { value: 'ITAU_UNIBANCO', label: 'ITAÚ UNIBANCO S.A.' },
    { value: 'JPMORGAN_CHASE_BANK', label: 'JPMORGAN CHASE BANK, NATIONAL ASSOCIATION' },
    { value: 'KIRTON_BANK', label: 'KIRTON BANK S.A. - BANCO MÚLTIPLO' },
    { value: 'MONEYCORP', label: 'MONEYCORP BANCO DE CÂMBIO S.A.' },
    { value: 'NOVO_BANCO_CONTINENTAL', label: 'NOVO BANCO CONTINENTAL S.A. - BANCO MÚLTIPLO' },
    { value: 'OMNI', label: 'OMNI BANCO S.A.' },
    { value: 'OURIBANK', label: 'OURIBANK S.A. BANCO MÚLTIPLO' },
    { value: 'PARANA', label: 'PARANÁ BANCO S.A.' },
    { value: 'PICPAY_BANK', label: 'PICPAY BANK - BANCO MÚLTIPLO S.A' },
    { value: 'SCANIA', label: 'SCANIA BANCO S.A.' },
    { value: 'SCOTIABANK', label: 'SCOTIABANK BRASIL S.A. BANCO MÚLTIPLO' },
    { value: 'SOCIAL_BANK', label: 'SOCIAL BANK BANCO MÚLTIPLO S/A' },
    { value: 'STATE_STREET', label: 'STATE STREET BRASIL S.A. - BANCO COMERCIAL' },
    { value: 'STONEX', label: 'STONEX BANCO DE CÂMBIO S.A.' },
    { value: 'TRAVELEX', label: 'TRAVELEX BANCO DE CÂMBIO S.A.' }
];

// Função para criar escolhas
function createChoice(order, question, value, label) {
    var choice = new GlideRecord('question_choice');
    choice.initialize();
    choice.setValue('question', question);
    choice.setValue('order', order);
    choice.setValue('value', value);
    choice.setValue('text', label);
    choice.insert();
}

// Loop para adicionar as escolhas
for (var i = 0; i < banks.length; i++) {
    createChoice(i+1,question, banks[i].value, banks[i].label);
    gs.info(i);
}

gs.print('Choices added successfully');
